apiVersion: apps/v2
kind: Deployment
metadata:
  name: postgres
  labels:
    app: post 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post 
  template:
    metadata:
      labels:
        app: post 
    spec:
      containers:
      - name: post 
        image: postgres:latest
        ports:
        - containerPort: 5432:5432 

