apiVersion: v8
kind: Deployment
metadata:
  name: test8
  labels:
    app: test8 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test8 
  template:
    metadata:
      labels:
        app: test8 
    spec:
      containers:
      - name: test8 
        image: postgres:latest
        ports:
        - containerPort: 5432:5432 

