builds:
    - env:
          - CGO_ENABLED=0
      goos: [linux, windows]
      goarch: [amd64]
      main: .
      binary: gorvus
      ldflags:
          - -s -w -X main.Version={{.Version}}

archives:
    - format: binary
      name_template: "gorvus_{{.Os}}_{{.Arch}}"
    - format: zip
      name_template: "gorvus_{{.Version}}_{{.Os}}_{{.Arch}}.zip"
      os: windows

release:
    github:
        owner: "{{ .GitHubOwner }}"
        repo: "{{ .GitHubRepository }}"
