# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
        
    - name: Get dependencies
      run: go get -v -t -d ./...
    
    - name: Build
      run: go build -v -o gorvus ./...

    - name: Test Dockerfile Generation
      run: ./gorvus gend -l go -p test

    - name: Test Compose Add command
      run : ./gorvus compose add -s test -i postgres:latest -p 5432:5432 -o host -e test=test -n network

    - name: Test Compose Add-net command
      run: ./gorvus compose add-net -d bridge -n network -x network-test

  
