name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

